/**
 * @roamfit/data — exercise library, progression families, schemas, and validators.
 *
 * The bundled content itself lives in packages/data/library/*.json (196+ exercise records,
 * the 8 v1 progression ladders — wave-01b-content.md, spec.md §4.1, §4.2, §6.6). This module
 * re-exports the shared types and the raw library data for consumers (the engine, tests).
 */
import exercisesJson from '../library/exercises.json';
import familiesJson from '../library/families.json';
import figuresJson from '../library/figures.json';
import type { ExerciseLibrary, FamilyLibrary } from './schema';

export * from './schema';

export const exerciseLibrary = exercisesJson as unknown as ExerciseLibrary;
export const familyLibrary = familiesJson as unknown as FamilyLibrary;

/**
 * Bundled in-house line-art demo figures (§11.4 tier 2) — exercise_id -> raw SVG markup string.
 * 100% offline coverage over `exerciseLibrary`, enforced by `validate.ts`. Generated by
 * `tools/generate-figures.ts`; do not hand-edit `library/figures.json`.
 *
 * This is a *static registry*, not a filesystem/asset-pipeline lookup — the whole map is a single
 * JSON import, so it resolves under Metro exactly like `exerciseLibrary` already does, with zero
 * network and zero runtime file access. A consumer renders the string directly (e.g. via
 * react-native-svg's `SvgXml`) rather than `require`-ing a path per exercise.
 */
export const figureLibrary = figuresJson as unknown as Record<string, string>;
